import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateReminderTables1762095734668 implements MigrationInterface {
    name = 'CreateReminderTables1762095734668'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bloqueios" DROP CONSTRAINT "bloqueios_barbeiro_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "barber_working_hours" DROP CONSTRAINT "barber_working_hours_barberId_fkey"`);
        await queryRunner.query(`ALTER TABLE "barbers" DROP CONSTRAINT "barbers_businessId_fkey"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "profiles_businessId_fkey"`);
        await queryRunner.query(`ALTER TABLE "client_contacts" DROP CONSTRAINT "client_contacts_businessId_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_businessId_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_serviceId_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_barberId_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_clientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "appointments_clientContactId_fkey"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "services_businessId_fkey"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "settings_businessId_fkey"`);
        await queryRunner.query(`ALTER TABLE "working_hours" DROP CONSTRAINT "working_hours_businessId_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bloqueios_barber"`);
        await queryRunner.query(`DROP INDEX "public"."idx_barber_working_hours_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_barbers_business"`);
        await queryRunner.query(`DROP INDEX "public"."idx_profiles_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_client_contacts_business"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_client"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_barber"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_business"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_startDate"`);
        await queryRunner.query(`DROP INDEX "public"."idx_appointments_client_contact"`);
        await queryRunner.query(`DROP INDEX "public"."idx_services_business"`);
        await queryRunner.query(`ALTER TABLE "client_contacts" DROP CONSTRAINT "UQ_client_contacts_business_phone"`);
        await queryRunner.query(`CREATE TYPE "public"."reminder_settings_type_enum" AS ENUM('CONFIRMATION', 'PRE_APPOINTMENT', 'POST_APPOINTMENT', 'RESCHEDULING')`);
        await queryRunner.query(`CREATE TABLE "reminder_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" integer NOT NULL, "type" "public"."reminder_settings_type_enum" NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "hoursBeforeAppointment" text NOT NULL DEFAULT '[]', "timezone" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8967b53d42011ef8628dc889979" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reminder_templates_type_enum" AS ENUM('CONFIRMATION', 'PRE_APPOINTMENT', 'POST_APPOINTMENT', 'RESCHEDULING')`);
        await queryRunner.query(`CREATE TABLE "reminder_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessId" integer NOT NULL, "type" "public"."reminder_templates_type_enum" NOT NULL, "message" text NOT NULL, "variables" text, "active" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d4e1f6b10a440630468fcb0a451" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reminder_logs_type_enum" AS ENUM('CONFIRMATION', 'PRE_APPOINTMENT', 'POST_APPOINTMENT', 'RESCHEDULING')`);
        await queryRunner.query(`CREATE TYPE "public"."reminder_logs_status_enum" AS ENUM('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "reminder_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "appointmentId" integer NOT NULL, "clientContactId" integer, "type" "public"."reminder_logs_type_enum" NOT NULL, "status" "public"."reminder_logs_status_enum" NOT NULL DEFAULT 'PENDING', "scheduledAt" TIMESTAMP, "sentAt" TIMESTAMP, "messageId" character varying, "message" text, "error" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b829028c9baa35c1f66188c186d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "clientContactId" integer, "profileId" integer, "remindersEnabled" boolean NOT NULL DEFAULT true, "optOutDate" TIMESTAMP, "preferredLanguage" character varying NOT NULL DEFAULT 'pt-BR', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0d06e691326d586481f28447cfb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "bloqueios" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bloqueios" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "barber_working_hours" ALTER COLUMN "closed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "barbers" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "barbers" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "barbers" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum" RENAME TO "user_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."profiles_role_enum" AS ENUM('ADMIN', 'BARBERSHOP', 'CLIENT')`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" TYPE "public"."profiles_role_enum" USING "role"::"text"::"public"."profiles_role_enum"`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" SET DEFAULT 'CLIENT'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "serviceId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "barberId" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."appointment_status_enum" RENAME TO "appointment_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."appointments_status_enum" AS ENUM('pending', 'confirmed', 'canceled')`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" TYPE "public"."appointments_status_enum" USING "status"::"text"::"public"."appointments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."appointment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."appointment_origin_enum" RENAME TO "appointment_origin_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."appointments_source_enum" AS ENUM('web', 'whatsapp')`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "source" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "source" TYPE "public"."appointments_source_enum" USING "source"::"text"::"public"."appointments_source_enum"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "source" SET DEFAULT 'web'`);
        await queryRunner.query(`DROP TYPE "public"."appointment_origin_enum_old"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "reminderHours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "enableReminders" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "allowCancellation" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "cancellationDeadlineHours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "allowReschedule" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "rescheduleDeadlineHours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "autoConfirmAppointments" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "businesses" ALTER COLUMN "createdAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "businesses" ALTER COLUMN "updatedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "working_hours" ALTER COLUMN "closed" SET NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4dcb78a944463de3b0b1efbf8d" ON "client_contacts" ("businessId", "phone") `);
        await queryRunner.query(`ALTER TABLE "barber_working_hours" ADD CONSTRAINT "UQ_ad1d9b18b159805ed6918c5a9a4" UNIQUE ("barberId", "dayOfWeek")`);
        await queryRunner.query(`ALTER TABLE "bloqueios" ADD CONSTRAINT "FK_d91c2a9ec893ead464e5be8b9d3" FOREIGN KEY ("barbeiro_id") REFERENCES "barbers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "barber_working_hours" ADD CONSTRAINT "FK_ca651a56b51af70956490393f07" FOREIGN KEY ("barberId") REFERENCES "barbers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "barbers" ADD CONSTRAINT "FK_b789cb621e55a36d7a7f51b8d26" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_c4b912210471a0c419de2848cb4" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ADD CONSTRAINT "FK_bab1602f08b57f50969776bf78a" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_7bf98fac7b5260d4b1a44f938d6" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_f77953c373efb8ab146d98e90c3" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_40ba2a25066184a434d47cdd5c2" FOREIGN KEY ("barberId") REFERENCES "barbers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_c4dbd8eb292b83b5dc67be3cf45" FOREIGN KEY ("clientId") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_a0b3944545b24f99afe1d795907" FOREIGN KEY ("clientContactId") REFERENCES "client_contacts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "FK_b6f9b3d2818d75f5839d70cbb18" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "FK_d1360503c0a1401e60086349795" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminder_settings" ADD CONSTRAINT "FK_6254a9ebabd209562f0167edf66" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminder_templates" ADD CONSTRAINT "FK_79af4a6f2f1ebf72f5a6bcd39c9" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "working_hours" ADD CONSTRAINT "FK_0915ec9930d65981efaf5ec661a" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminder_logs" ADD CONSTRAINT "FK_5fd19e5f89c3f15c5cd8615d5fd" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reminder_logs" ADD CONSTRAINT "FK_2cf5bce17a55a79a93f41e44256" FOREIGN KEY ("clientContactId") REFERENCES "client_contacts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_preferences" ADD CONSTRAINT "FK_6c62ebb8fede991ff910a0024ce" FOREIGN KEY ("clientContactId") REFERENCES "client_contacts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_preferences" ADD CONSTRAINT "FK_242e2f6c16edd0b8b231658dcdc" FOREIGN KEY ("profileId") REFERENCES "profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "client_preferences" DROP CONSTRAINT "FK_242e2f6c16edd0b8b231658dcdc"`);
        await queryRunner.query(`ALTER TABLE "client_preferences" DROP CONSTRAINT "FK_6c62ebb8fede991ff910a0024ce"`);
        await queryRunner.query(`ALTER TABLE "reminder_logs" DROP CONSTRAINT "FK_2cf5bce17a55a79a93f41e44256"`);
        await queryRunner.query(`ALTER TABLE "reminder_logs" DROP CONSTRAINT "FK_5fd19e5f89c3f15c5cd8615d5fd"`);
        await queryRunner.query(`ALTER TABLE "working_hours" DROP CONSTRAINT "FK_0915ec9930d65981efaf5ec661a"`);
        await queryRunner.query(`ALTER TABLE "reminder_templates" DROP CONSTRAINT "FK_79af4a6f2f1ebf72f5a6bcd39c9"`);
        await queryRunner.query(`ALTER TABLE "reminder_settings" DROP CONSTRAINT "FK_6254a9ebabd209562f0167edf66"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "FK_d1360503c0a1401e60086349795"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "FK_b6f9b3d2818d75f5839d70cbb18"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_a0b3944545b24f99afe1d795907"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_c4dbd8eb292b83b5dc67be3cf45"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_40ba2a25066184a434d47cdd5c2"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_f77953c373efb8ab146d98e90c3"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_7bf98fac7b5260d4b1a44f938d6"`);
        await queryRunner.query(`ALTER TABLE "client_contacts" DROP CONSTRAINT "FK_bab1602f08b57f50969776bf78a"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_c4b912210471a0c419de2848cb4"`);
        await queryRunner.query(`ALTER TABLE "barbers" DROP CONSTRAINT "FK_b789cb621e55a36d7a7f51b8d26"`);
        await queryRunner.query(`ALTER TABLE "barber_working_hours" DROP CONSTRAINT "FK_ca651a56b51af70956490393f07"`);
        await queryRunner.query(`ALTER TABLE "bloqueios" DROP CONSTRAINT "FK_d91c2a9ec893ead464e5be8b9d3"`);
        await queryRunner.query(`ALTER TABLE "barber_working_hours" DROP CONSTRAINT "UQ_ad1d9b18b159805ed6918c5a9a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4dcb78a944463de3b0b1efbf8d"`);
        await queryRunner.query(`ALTER TABLE "working_hours" ALTER COLUMN "closed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "businesses" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "businesses" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "businesses" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "autoConfirmAppointments" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "rescheduleDeadlineHours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "allowReschedule" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "cancellationDeadlineHours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "allowCancellation" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "enableReminders" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "settings" ALTER COLUMN "reminderHours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "services" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."appointment_origin_enum_old" AS ENUM('web', 'whatsapp')`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "source" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "source" TYPE "public"."appointment_origin_enum_old" USING "source"::"text"::"public"."appointment_origin_enum_old"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "source" SET DEFAULT 'web'`);
        await queryRunner.query(`DROP TYPE "public"."appointments_source_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."appointment_origin_enum_old" RENAME TO "appointment_origin_enum"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."appointment_status_enum_old" AS ENUM('pending', 'confirmed', 'canceled')`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" TYPE "public"."appointment_status_enum_old" USING "status"::"text"::"public"."appointment_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."appointments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."appointment_status_enum_old" RENAME TO "appointment_status_enum"`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "barberId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointments" ALTER COLUMN "serviceId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "updatedAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum_old" AS ENUM('ADMIN', 'BARBERSHOP', 'CLIENT')`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" TYPE "public"."user_role_enum_old" USING "role"::"text"::"public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "profiles" ALTER COLUMN "role" SET DEFAULT 'CLIENT'`);
        await queryRunner.query(`DROP TYPE "public"."profiles_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum_old" RENAME TO "user_role_enum"`);
        await queryRunner.query(`ALTER TABLE "barbers" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "barbers" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "barbers" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "barber_working_hours" ALTER COLUMN "closed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bloqueios" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bloqueios" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`DROP TABLE "client_preferences"`);
        await queryRunner.query(`DROP TABLE "reminder_logs"`);
        await queryRunner.query(`DROP TYPE "public"."reminder_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reminder_logs_type_enum"`);
        await queryRunner.query(`DROP TABLE "reminder_templates"`);
        await queryRunner.query(`DROP TYPE "public"."reminder_templates_type_enum"`);
        await queryRunner.query(`DROP TABLE "reminder_settings"`);
        await queryRunner.query(`DROP TYPE "public"."reminder_settings_type_enum"`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ADD CONSTRAINT "UQ_client_contacts_business_phone" UNIQUE ("businessId", "phone")`);
        await queryRunner.query(`CREATE INDEX "idx_services_business" ON "services" ("businessId") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_client_contact" ON "appointments" ("clientContactId") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_startDate" ON "appointments" ("startDate") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_business" ON "appointments" ("businessId") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_barber" ON "appointments" ("barberId") `);
        await queryRunner.query(`CREATE INDEX "idx_appointments_client" ON "appointments" ("clientId") `);
        await queryRunner.query(`CREATE INDEX "idx_client_contacts_business" ON "client_contacts" ("businessId") `);
        await queryRunner.query(`CREATE INDEX "idx_profiles_email" ON "profiles" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_barbers_business" ON "barbers" ("businessId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_barber_working_hours_unique" ON "barber_working_hours" ("barberId", "dayOfWeek") `);
        await queryRunner.query(`CREATE INDEX "idx_bloqueios_barber" ON "bloqueios" ("barbeiro_id") `);
        await queryRunner.query(`ALTER TABLE "working_hours" ADD CONSTRAINT "working_hours_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "settings_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "services_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_clientContactId_fkey" FOREIGN KEY ("clientContactId") REFERENCES "client_contacts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_barberId_fkey" FOREIGN KEY ("barberId") REFERENCES "barbers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "appointments_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_contacts" ADD CONSTRAINT "client_contacts_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "profiles_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "barbers" ADD CONSTRAINT "barbers_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "barber_working_hours" ADD CONSTRAINT "barber_working_hours_barberId_fkey" FOREIGN KEY ("barberId") REFERENCES "barbers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bloqueios" ADD CONSTRAINT "bloqueios_barbeiro_id_fkey" FOREIGN KEY ("barbeiro_id") REFERENCES "barbers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
